# Generated by Django 3.1.7 on 2021-03-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingoodhands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1000)),
                ('type', models.CharField(choices=[('FUND', 'fundacja'), ('LOCAL', 'zbiórka lokalna'), ('ORG', 'organizacja pozarządowa')], default='FUND', max_length=5)),
                ('categories', models.ManyToManyField(to='ingoodhands.Category')),
            ],
        ),
    ]
