# Generated by Django 3.1.7 on 2021-03-24 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingoodhands', '0002_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('ORG', 'organizacja pozarządowa'), ('FUND', 'fundacja'), ('LOCAL', 'zbiórka lokalna')], default='FUND', max_length=5),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=24)),
                ('zip_code', models.CharField(max_length=6)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.CharField(max_length=128)),
                ('categories', models.ManyToManyField(to='ingoodhands.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingoodhands.institution')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
