# Generated by Django 3.1.7 on 2021-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingoodhands', '0003_auto_20210324_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('LOCAL', 'zbiórka lokalna'), ('ORG', 'organizacja pozarządowa'), ('FOUND', 'fundacja')], default='FOUND', max_length=5),
        ),
    ]
